//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_FoodDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCardItem
    {
        public int id { get; set; }
        public Nullable<int> dishid { get; set; }
        public int price { get; set; }
        public string DeliveryCardId { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
