//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_FoodDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int id { get; set; }
        public int orderId { get; set; }
        public int dishId { get; set; }
        public long price { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
