//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_FoodDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Dish = new HashSet<Dish>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string shortDesc { get; set; }
        public string img { get; set; }
        public string longDesc { get; set; }
        public string workingTime { get; set; }
        public string address { get; set; }
        public bool isFavourite { get; set; }
        public int dishCategoryID { get; set; }
        public Nullable<int> FoodCategoryid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dish> Dish { get; set; }
        public virtual FoodCategory FoodCategory { get; set; }
    }
}
